@echo off

(
  echo WOT-BUILTIN,2
  echo # corrections for man1aq_ revived
  echo #
  echo # autogenerated by make_builtin-2.bat
  echo #
  echo # all tanks of special category are move to premium category
  echo #

  for /f "tokens=1 delims=," %%L in ( '"findstr ,special, Exported\Exported-WotBuiltIn-0.csv"') do (
    echo %%L,,,,premium
  )

  findstr ,,,,,,del WotBuiltIn-1.csv


) > WotBuiltIn-2.csv
